name: moviedb
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  equatable: 2.0.5
  either_dart: ^0.4.0
  dependencies:
  bloc_test: ^9.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
git
flutter:

  uses-material-design: true

